export default resources = {
    arm: require('../../assets/arm2.png'),
    legs: require('../../assets/legs.png'),
    core: require('../../assets/strong.png'),
    brain: require('../../assets/brain.png'),
    cardio: require('../../assets/cardio.png'),
    dip_bar: require('../../assets/dip-bar.png'),
    background: require('../../assets/IMG_6466.png'),
    rings: require('../../assets/olympic-rings.png'),
    pull_muscle: require('../../assets/pull-up.png'),
    push_up_icon: require('../../assets/push-up.png'),
    meditation: require('../../assets/yoga-pose.png'),
    logo: require('../../assets/espartania_logo_1.png'),
    logo2: require('../../assets/espartania_logo_2.png'),
    pull_up_icon: require('../../assets/body-weight.png'),
    headerLogo: require('../../assets/esparanita_logo_3.png'),
    logo_transparent_3: require('../../assets/logo_transparent_3.png'),
    headerLogo2: require('../../assets/espartania_black_and_white.png'),
    logo_transparent: require('../../assets/espartania_transparent_1.png'),
    logo_transparent_2: require('../../assets/espartania_transparent_2.png'),
} 